// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FolderHasher.Model.Serialization
{

    using global::System;
    using global::FlatBuffers;

    public struct FileHashDatabaseSerialized : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static FileHashDatabaseSerialized GetRootAsFileHashDatabaseSerialized(ByteBuffer _bb) { return GetRootAsFileHashDatabaseSerialized(_bb, new FileHashDatabaseSerialized()); }
        public static FileHashDatabaseSerialized GetRootAsFileHashDatabaseSerialized(ByteBuffer _bb, FileHashDatabaseSerialized obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public FileHashDatabaseSerialized __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public FileHashSerialized? FileHashes(int j) { int o = __p.__offset(4); return o != 0 ? (FileHashSerialized?)(new FileHashSerialized()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int FileHashesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<FileHashDatabaseSerialized> CreateFileHashDatabaseSerialized(FlatBufferBuilder builder,
            VectorOffset fileHashesOffset = default(VectorOffset))
        {
            builder.StartObject(1);
            FileHashDatabaseSerialized.AddFileHashes(builder, fileHashesOffset);
            return FileHashDatabaseSerialized.EndFileHashDatabaseSerialized(builder);
        }

        public static void StartFileHashDatabaseSerialized(FlatBufferBuilder builder) { builder.StartObject(1); }
        public static void AddFileHashes(FlatBufferBuilder builder, VectorOffset fileHashesOffset) { builder.AddOffset(0, fileHashesOffset.Value, 0); }
        public static VectorOffset CreateFileHashesVector(FlatBufferBuilder builder, Offset<FileHashSerialized>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static void StartFileHashesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<FileHashDatabaseSerialized> EndFileHashDatabaseSerialized(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<FileHashDatabaseSerialized>(o);
        }
        public static void FinishFileHashDatabaseSerializedBuffer(FlatBufferBuilder builder, Offset<FileHashDatabaseSerialized> offset) { builder.Finish(offset.Value); }
    };


}
